### ISSUE TITLE
Handle site localization in client to support automatic language switching

### ISSUE THREAD

**Issue by baka-gourd** [saicaca/fuwari#104]
Nowadays, the language of the site is determined at rendering time, which is not friendly to multilingual versions.
can use `navigator.language` to detect it
Also astro should be able to implement automatic route switching between aaa.zh-CN.md, and aaa.md, but I've looked at astro's examples and haven't come up with an elegant solution for storing multiple language versions.

**Comment by saicaca** [comment]
Thank you for your suggestion, but I currently don't plan to implement it. Because It requires a lot of changes, and I think it is not very common for a blog site to have versions in different languages.
