### ISSUE TITLE
Banner无法调整位置

### ISSUE THREAD

**Issue by Lry722** [saicaca/fuwari#105]
老版本的Banner有个position的配置项，新版本中似乎没看到对应的东西。
我希望设置 object-position: top 的效果，虽然自己改一下也行，但似乎加进配置项里会更好一些。

**Comment by Lry722** [comment]
还有一点就是，老版本的主页Banner会比文章页面的更大一点，新版本这个效果也没了...

**Comment by saicaca** [comment]
> 老版本的Banner有个position的配置项，新版本中似乎没看到对应的东西。

object-position 是我忘记了，稍后会加上。

> 还有一点就是，老版本的主页Banner会比文章页面的更大一点，新版本这个效果也没了...

我是希望保留这个设计的，但遇到一个问题。现在页面之间的切换有 transition 动画，我需要让 Banner 高度变化的 transition 和页面切换的 transition 同步执行，但我目前还没找到办法。

**Comment by Lry722** [comment]
> > 老版本的Banner有个position的配置项，新版本中似乎没看到对应的东西。
> 
> object-position 是我忘记了，稍后会加上。
> 
> > 还有一点就是，老版本的主页Banner会比文章页面的更大一点，新版本这个效果也没了...
> 
> 我是希望保留这个设计的，但遇到一个问题。现在页面之间的切换有 transition 动画，我需要让 Banner 高度变化的 transition 和页面切换的 transition 同步执行，但我目前还没找到办法。

我已经把position加上了，等会儿发个pr

**Comment by saicaca** [comment]
> 还有一点就是，老版本的主页Banner会比文章页面的更大一点，新版本这个效果也没了...

这个特性也加回来了 f28ad1b8e61cb8891e46b8d6a8bf93fac504ae7b
