### ISSUE TITLE
Cannot build site locally, "pnpm dev" fails when trying to load site

### ISSUE THREAD

**Issue by lyfja** [saicaca/fuwari#108]
Terminal output:

```
> fuwari@0.0.1 dev /var/home/lyfja/Website/fuwari
> astro dev

(node:48630) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)

 astro  v4.4.15 ready in 740 ms

┃ Local    http://localhost:4321/
┃ Network  use --host to expose

00:32:49 watching for file changes...
00:33:12 [astro-icon] Loaded icons from fa6-brands, fa6-regular, fa6-solid, material-symbols
00:33:15 [200] / 1133ms
munmap_chunk(): invalid pointer
 ELIFECYCLE  Command failed.
```

I can visit the site (screenshot), but once I do the build fails and the connection is gone.

![Bildschirmfoto vom 2024-06-19 00-38-10](https://github.com/saicaca/fuwari/assets/45209212/5a3cb97c-ed86-4cff-a8cf-b10abc1750d9)

It's a clean clone from the git repo, no files were modified.

**Comment by Kurumi30** [comment]
See #23

**Comment by Kurumi30** [comment]
> Terminal output:
> 
> ```
> > fuwari@0.0.1 dev /var/home/lyfja/Website/fuwari
> > astro dev
> 
> (node:48630) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
> (Use `node --trace-deprecation ...` to show where the warning was created)
> 
>  astro  v4.4.15 ready in 740 ms
> 
> ┃ Local    http://localhost:4321/
> ┃ Network  use --host to expose
> 
> 00:32:49 watching for file changes...
> 00:33:12 [astro-icon] Loaded icons from fa6-brands, fa6-regular, fa6-solid, material-symbols
> 00:33:15 [200] / 1133ms
> munmap_chunk(): invalid pointer
>  ELIFECYCLE  Command failed.
> ```
> 
> I can visit the site (screenshot), but once I do the build fails and the connection is gone.
> 
> ![Bildschirmfoto vom 2024-06-19 00-38-10](https://private-user-images.githubusercontent.com/45209212/340858923-5a3cb97c-ed86-4cff-a8cf-b10abc1750d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3NjIzMTAsIm5iZiI6MTcxODc2MjAxMCwicGF0aCI6Ii80NTIwOTIxMi8zNDA4NTg5MjMtNWEzY2I5N2MtZWQ4Ni00Y2ZmLWE4Y2YtYjEwYWJjMTc1MGQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDAxNTMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlZTYzYTc5MDBiZmQxMWEwNTk4ZTdkN2RmYzRlMTVlNjE2ZmM3OGQ2MzljYmNlOGM5M2Q4M2Q3YjA5YmU2ZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RmWI0HyX3PIQdFmLUImlQqYEITVuQg6fabeE-hLMR4M)
> 
> It's a clean clone from the git repo, no files were modified.

See #23
