### ISSUE TITLE
Issue with GitHub Repository Cards

### ISSUE THREAD

**Issue by HyperSkys** [saicaca/fuwari#119]
If you visit your `Markdown Extended Features` post on your own site (https://fuwari.vercel.app/posts/markdown-extended/) it will fail to load any details on the GitHub repository and it will also upon clicking it redirect to a 404: NOT_FOUND page.

**Comment by saicaca** [comment]
It seems to be working fine. The issue you encountered might be due to a failure when calling the GitHub API or hitting the GitHub API rate limit.

**Comment by HyperSkys** [comment]
> It seems to be working fine. The issue you encountered might be due to a failure when calling the GitHub API or hitting the GitHub API rate limit.

Yep seems like the API went down for an hour yesterday
