### ISSUE TITLE
I Created a Blog Theme for Mix-Space Based on Fuwari

### ISSUE THREAD

**Issue by TNXG** [saicaca/fuwari#120]
Hi, thank you for providing the Fuwari static blog template! I have made some modifications to it, creating a new theme suitable for [Mix-Space](https://github.com/mx-space). I've named the new theme [Kasumino](https://github.com/TNXG/Kasumino) (meaning "mist"), inspired by the Japanese pronunciation of Fuwari's imagery.

PS: I feel quite embarrassed looking at my own modifications.

---

感谢佬提供的 Fuwari 静态博客模板！我基于 Fuwari 进行了二次开发，做了一些修改，使其适用于 [Mix-Space](https://github.com/mx-space)。我将新主题命名为 [Kasumino](https://github.com/TNXG/Kasumino)（雾之），这个名字来源于 Fuwari 的某种意象（雾）的日语发音。

PS：我修改的代码自己看都感觉写的依托www

**Comment by davidvkimball** [comment]
Love your site! I'm getting an error though when trying to load your [about page](https://kasumino.vercel.app/about/). It looks like it is attempting to redirect to your [浅谈吾导先路活动 post](https://kasumino.vercel.app/posts/game/3.html) but it only works half the time.

**Comment by TNXG** [comment]
> Love your site! I'm getting an error though when trying to load your [about page](https://kasumino.vercel.app/about/). It looks like it is attempting to redirect to your [浅谈吾导先路活动 post](https://kasumino.vercel.app/posts/game/3.html) but it only works half the time.

I'm having difficulty reliably reproducing the path issue, making it hard to pinpoint the cause of the problem in the modified version. Moreover, there isn't a /about/ route available; the profile click should navigate to the /about-me/ page.

---

遇到的路径问题很难得到稳定的复现，我很难定位这些问题在修改版中出现的原因（况且并没有/about/路由可供使用，点击头像跳转的关于界面应该是/about-me/）
