### ISSUE TITLE
怎么加一个网页访问次数，和访问人数的统计

### ISSUE THREAD

**Issue by 2535521265** [saicaca/fuwari#121]
如题

**Comment by Lry722** [comment]
这好像是个静态博客框架，搞这个应该不太方便

**Comment by DarkModest** [comment]
可以用Cloudflare的Web Analytics, 不过要在每一个网页上插入Cloudflare的JS片段。

**Comment by saicaca** [comment]
静态博客自身无法支持此功能，可以自行尝试通过 Waline 等第三方框架引入
