### ISSUE TITLE
侧边栏显示问题

### ISSUE THREAD

**Issue by TasLR** [saicaca/fuwari#126]
能否为主页的右栏内容添加单独的滚动条，实现左栏在滚动的时候一直是固定不动，只移动右栏的内容，而不是滚动整个页面，或者能给点思路应该怎么处理，谢谢啦

**Comment by saicaca** [comment]
不确定我有没有正确理解问题，目前侧边栏的标签和目录组件确实是固定不动的，如果你是说希望个人信息也固定不动，可以把 `SideBar.astro` 里的 `<Profile>` 也放到下面那个带 `sticky` 类的 `div` 里

https://github.com/saicaca/fuwari/blob/f438ea4252ec3773038648747a085d0dfac89a25/src/components/widget/SideBar.astro#L8-L16

**Comment by TasLR** [comment]
好的，谢谢



在 2024-07-20 22:37:12，"saica.go" ***@***.***> 写道：

不确定我有没有正确理解问题，目前侧边栏的标签和目录组件确实是固定不动的，如果你是说希望个人信息也固定不动，可以把 SideBar.astro 里的 <Profile> 也放到下面那个带 sticky 类的 div 里

https://github.com/saicaca/fuwari/blob/f438ea4252ec3773038648747a085d0dfac89a25/src/components/widget/SideBar.astro#L8-L16
