### ISSUE TITLE
github卡片失效了

### ISSUE THREAD

**Issue by XuYiHan30319** [saicaca/fuwari#127]
<img width="823" alt="image" src="https://github.com/user-attachments/assets/a8ca9d1c-5c51-406f-b8d6-70c589043d35">

**Comment by XuYiHan30319** [comment]
点进去变成404了

**Comment by saicaca** [comment]
GitHub Repo 卡片内容加载失败通常是 GitHub API 限流导致的。在加载失败的情况下点击卡片会跳到 404 页面确实是 bug， bd4f0e8 已修复
