### ISSUE TITLE
代码块符号显示不正常

### ISSUE THREAD

**Issue by Motues** [saicaca/fuwari#128]
### 代码块里面的`<=`，`>=`，`!=`，`==`全部被渲染成公式的格式，就像下面这样。
![image](https://github.com/user-attachments/assets/447e4f30-ed17-41ec-bea5-1696da581ed1)

**Comment by HyperCherry** [comment]
这应该是因为使用了字体[JetBrains Mono](https://www.jetbrains.com/lp/mono/)中的连笔字，更换一个字体就不会显示成这样了，你可以试试修改https://github.com/saicaca/fuwari/blob/f438ea4252ec3773038648747a085d0dfac89a25/src/components/misc/Markdown.astro#L155
这一行代码来更换字体

**Comment by saicaca** [comment]
这是主题使用的代码字体 JetBrains Mono 自身的 ligatures 效果。除了更换字体以外，在上述 css 位置设置 `font-variant-ligatures: none` 也可以禁用 ligatures

**Comment by Motues** [comment]
谢谢谢谢，问题已经解决了😀
