### ISSUE TITLE
Errors on imports with `.ts` extension

### ISSUE THREAD

**Issue by Katsuyuki-Karasawa** [saicaca/fuwari#13]
There are quite a few errors, but I believe this is due to default export.
I will send a PR to fix these, but it may take some time as they are a bit numerous!
![image](https://github.com/saicaca/fuwari/assets/70247011/ad14e088-d504-4cab-befb-85c95980843c)
![image](https://github.com/saicaca/fuwari/assets/70247011/a54d5414-7ae4-43cb-94f2-88901488d072)

As it says "An import path can only end with a .ts extension when `allowImportingTsExtensions` is enabled", I think it is OK if you change ts.config, but I personally don't recommend it

**Comment by saicaca** [comment]
I think it's ok to remove the extensions. Thank you for your help.😄

**Comment by saicaca** [comment]
I am doing a code cleanup for the whole repo. So I think it will be better for me to address this issue along the way.

**Comment by Katsuyuki-Karasawa** [comment]
OK 👍

**Comment by saicaca** [comment]
Fixed in #14

**Comment by Katsuyuki-Karasawa** [comment]
👍 👍
