### ISSUE TITLE
Azure部署报错

### ISSUE THREAD

**Issue by Mrzqd** [saicaca/fuwari#152]
您好，感谢您的开源。我今日在更新文章的时候，GitHub actions部署报错了。日志如下：
Removing existing manifest file
Creating directory for command manifest file if it does not exist
Creating a manifest file...
Node Build Command Manifest file created.

Using Node version:
v20.15.1

Using Npm version:
10.7.0

Running 'npm install'...

npm warn deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm warn deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
npm warn deprecated @babel/plugin-proposal-class-properties@7.12.1: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated rollup-plugin-terser@7.0.2: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-terser

added 1106 packages, and audited 1107 packages in 1m

316 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Running 'npm run build'...

> fuwari@0.0.1 build
> astro build && pagefind --site dist

5:22:47 AM [vite] Error when evaluating SSR module /github/workspace/astro.config.mjs: failed to import "astro-icon"
|- file:///github/workspace/node_modules/@iconify/tools/lib/svg/index.mjs:1
import cheerio from 'cheerio';
       ^^^^^^^
SyntaxError: The requested module 'cheerio' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:217:5)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async nodeImport (file:///github/workspace/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:52928:15)
    at async ssrImport (file:///github/workspace/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:52786:16)
    at async eval (/github/workspace/astro.config.mjs:8:31)
    at async instantiateModule (file:///github/workspace/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:52844:5)

[astro] Unable to load your Astro config

The requested module 'cheerio' does not provide an export named 'default'
  Stack trace:
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:134:21)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async ssrImport (file:///github/workspace/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:52786:16)
    at async instantiateModule (file:///github/workspace/node_modules/vite/dist/node/chunks/dep-NjL7WTE1.js:52844:5)

---End of Oryx build logs---
Oryx has failed to build the solution.

For further information, please visit the Azure Static Web Apps documentation at https://docs.microsoft.com/en-us/azure/static-web-apps/
If you believe this behavior is unexpected, please raise a GitHub issue at https://github.com/azure/static-web-apps/issues/
Exiting
可以帮我看一下嘛

**Comment by saicaca** [comment]
请使用 pnpm 而不是 npm 来安装依赖，本项目不保证能使用 npm 运行

**Comment by at-wr** [comment]
请参考这个 Astro-Icon 的 Issue: https://github.com/natemoo-re/astro-icon/issues/231
在 package.json 内指定
```json
  "overrides": {
    "astro-icon": {
      "@iconify/tools": "^4.0.0"
    }
  }
```

**Comment by Mrzqd** [comment]
> 请参考这个 Astro-Icon 的 Issue: [natemoo-re/astro-icon#231](https://github.com/natemoo-re/astro-icon/issues/231) 在 package.json 内指定
> 
> ```json
>   "overrides": {
>     "astro-icon": {
>       "@iconify/tools": "^4.0.0"
>     }
>   }
> ```

感谢回复，修改了Github Actions构建的方式，改成pnpm后可以啦
