### ISSUE TITLE
[建议]增加文章大纲

### ISSUE THREAD

**Issue by KinhoLeung** [saicaca/fuwari#156]
进入文章里后，在这里增加一个大纲，方便导航。
![无标题](https://github.com/user-attachments/assets/5336cfc7-1712-4f53-95f2-4c3fe7212d2b)

**Comment by pride7** [comment]
支持一下，我看到另外一个[blog](https://github.com/cirry/astro-yi)，在点进去之后会显示这个tableofcontent.
![image](https://github.com/user-attachments/assets/d19c4307-7ec4-46e7-b39d-ca2a97e5f015)
![image](https://github.com/user-attachments/assets/6e823a44-864a-4917-adda-b97f15cb752c)

**Comment by baka-gourd** [comment]
[#toc](https://github.com/saicaca/fuwari/pull/103)
soon🤣

**Comment by saicaca** [comment]
会加的

**Comment by saicaca** [comment]
Duplicate of #117
