### ISSUE TITLE
breaks after pnpm update

### ISSUE THREAD

**Issue by nvkomata** [saicaca/fuwari#158]
steps to reproduce:
1. clone yourself a fresh main branch of fuwari
2. use either system pnpm or one installed with npm
3. pnpm update
4. pnpm dev
5. see a lot of red in terminal caused by several things

are you not supposed to update your local repo ever? :P

**Comment by saicaca** [comment]
The latest release of `cheerio` broke `astro-icon 1.1.0`.

Modify the `package.json` by changing `"astro-icon": "1.1.0"` to `"astro-icon": "^1.1.0"`. Then run `pnpm update` again, and it should work.

**Comment by nvkomata** [comment]
> The latest release of `cheerio` broke `astro-icon 1.1.0`.
> 
> Modify the `package.json` by changing `"astro-icon": "1.1.0"` to `"astro-icon": "^1.1.0"`. Then run `pnpm update` again, and it should work.

worked, thank you. shouldn't it be changed upstream?

**Comment by saicaca** [comment]
> > The latest release of `cheerio` broke `astro-icon 1.1.0`.
> > Modify the `package.json` by changing `"astro-icon": "1.1.0"` to `"astro-icon": "^1.1.0"`. Then run `pnpm update` again, and it should work.
> 
> worked, thank you. shouldn't it be changed upstream?

I’m not quite sure what you mean by upstream. The issue has already been fixed in `astro-icon 1.1.1`. The `"^1.1.0"` above allows pnpm to update `astro-icon` to `1.1.1`. I’ll update the `package.json` in this project as well.

**Comment by nvkomata** [comment]
> > > The latest release of `cheerio` broke `astro-icon 1.1.0`.
> > > Modify the `package.json` by changing `"astro-icon": "1.1.0"` to `"astro-icon": "^1.1.0"`. Then run `pnpm update` again, and it should work.
> > 
> > 
> > worked, thank you. shouldn't it be changed upstream?
> 
> I’m not quite sure what you mean by upstream. The issue has already been fixed in `astro-icon 1.1.1`. The `"^1.1.0"` above allows pnpm to update `astro-icon` to `1.1.1`. I’ll update the `package.json` in this project as well.

oops sorry i meant "upstream" as in this repo. thank you
