### ISSUE TITLE
rss.xml cannot be parsed

### ISSUE THREAD

**Issue by RiverKy** [saicaca/fuwari#166]
From Google Search Console: 

> Unbound XML namespace prefix.
The XML Sitemap cannot be parsed because it contains one or more unbound namespace prefixes. For example, this error is generated when <xhtml:link> is found in a Sitemap without prior xmlns:xhtml="http://www.w3.org/1999/xhtml".

**Comment by saicaca** [comment]
Fixed in 1af707ee6a9fa6d70684eb6df3c8d4055532d959
