### ISSUE TITLE
Search issues caused by language settings

### ISSUE THREAD

**Issue by Yuuzi261** [saicaca/fuwari#167]
## Description

When I was searching, I found that I could not find the posts I had written, so I did some tests. Is this a bug?

## SiteConfig.lang = 'en' & language of posts = 'zh_TW'

I can only search About in English, and cannot search in Chinese.

![圖片](https://github.com/user-attachments/assets/204f0d7f-b188-4875-b594-66fd7d4ffd88)
![圖片](https://github.com/user-attachments/assets/af50661d-7457-4cf2-a4fc-16c941709d3f)

## SiteConfig.lang = 'zh_TW' & language of posts = 'zh_TW'

Everything works fine.

![圖片](https://github.com/user-attachments/assets/06b7a07f-31e6-4de3-896d-5c661e3dd687)
![圖片](https://github.com/user-attachments/assets/d51df91b-119c-4789-808d-05db4c479893)

## SiteConfig.lang = 'en' & language of posts = 'en'

After knowing that the problem was caused by language, I also set the language of the Chinese posts to English. I can search in English, but the preview of Chinese posts becomes strange, and I can't search in Chinese either.

![圖片](https://github.com/user-attachments/assets/e7494fea-0ae9-49c6-b1a1-d923e9c70914)
![圖片](https://github.com/user-attachments/assets/309589a9-d04c-4edd-bcf0-78ed242838a3)

## Conclusion

Because the `SiteConfig.lang` will affect the language of the UI setting, if I want the UI to be in English, but it will result in Chinese posts not being searched, it is not very convenient.

**Comment by saicaca** [comment]
Will look into it

**Comment by saicaca** [comment]
[Pagefind needs to know the webpage's language](https://pagefind.app/docs/multilingual/) to index the content correctly. By default, it is the site language in the `config.ts`. That is why posts in Chinese cannot be indexed when the site's language is set to `en`.

To fix it, you can specify the `lang` attribute in the front-matter of the post, which overrides the site language setting.

```yaml
lang: zh_TW
```
