### ISSUE TITLE
Error in rss.xml

### ISSUE THREAD

**Issue by Yuuzi261** [saicaca/fuwari#168]
## source code

[chore: update dependencies](https://github.com/saicaca/fuwari/commit/4518dbf0f8854796220687ddfdc01b05a589b972)

## error

XML 解析錯誤: 前置詞 (Prefix) 未繫結至 namespace
位置: http://localhost:4321/rss.xml
行號 1, 第 496 個字:

```<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"><channel><title>Fuwari</title><description>Demo Site</description><link>https://fuwari.vercel.app/</link><language>en</language><item><title>Markdown Extended Features</title><link>https://fuwari.vercel.app/posts/markdown-extended/</link><guid isPermaLink="true">https://fuwari.vercel.app/posts/markdown-extended/</guid><description>Read more about Markdown features in Fuwari</description><pubDate>Wed, 01 May 2024 00:00:00 GMT</pubDate><content:encoded/></item><item><title>Simple Guides for Fuwari</title><link>https://fuwari.vercel.app/posts/guide/</link><guid isPermaLink="true">https://fuwari.vercel.app/posts/guide/</guid><description>How to use this blog template.</description><pubDate>Mon, 01 Apr 2024 00:00:00 GMT</pubDate><content:encoded/></item><item><title>Markdown Example</title><link>https://fuwari.vercel.app/posts/markdown/</link><guid isPermaLink="true">https://fuwari.vercel.app/posts/markdown/</guid><description>A simple example of a Markdown blog post.</description><pubDate>Sun, 01 Oct 2023 00:00:00 GMT</pubDate><content:encoded/></item><item><title>Include Video in the Posts</title><link>https://fuwari.vercel.app/posts/video/</link><guid isPermaLink="true">https://fuwari.vercel.app/posts/video/</guid><description>This post demonstrates how to include embedded video in a blog post.</description><pubDate>Tue, 01 Aug 2023 00:00:00 GMT</pubDate><content:encoded/></item></channel></rss>```

**Comment by okatu-loli** [comment]
遇到同样的问题

**Comment by saicaca** [comment]
Fixed in 1af707ee6a9fa6d70684eb6df3c8d4055532d959
