### ISSUE TITLE
RSS Feed XML Parsing Error

### ISSUE THREAD

**Issue by okatu-loli** [saicaca/fuwari#171]
Encountered an error in rss.xml:
```
error on line 1 at column 478: Namespace prefix content on encoded is not defined
```

![image](https://github.com/user-attachments/assets/082a6baa-d323-44b2-80d5-54a37f2fadae)

**Steps to Reproduce**:
- Open the RSS feed URL (rss.xml). For example: https://cnqs.moe/rss.xml
- See the error message.

**Expected Result**: RSS feed displays correctly.

**Actual Result**: Error message appears.

**Comment by saicaca** [comment]
Fixed in 1af707ee6a9fa6d70684eb6df3c8d4055532d959
