### ISSUE TITLE
启用 Banner 时，Banner 和侧边栏的过渡动画丢帧

### ISSUE THREAD

**Issue by CosmoLau** [saicaca/fuwari#174]
启用 Banner 时，Banner 和侧边栏的过渡动画丢帧，导致这个问题的原因是 `duration-700` 这个间隔时间过长，以至于过渡动画不顺滑。性能分析如下，可以看到动画有明显的割裂：

![屏幕截图 2024-09-05 151011](https://github.com/user-attachments/assets/7ba7889b-623c-4880-97e4-983957bd105f)

这个问题在开发环境中尤为明显，在 https://fuwari.vercel.app/ DEMO 中虽然会好很多，但还是能感觉出有丢帧的问题。

我测试了多个 `duration` 间隔时间，在我的电脑上，只有 `duration-250` 及以下的间隔时间才能在开发环境中看不出来明显的割裂丢帧，这可能和 CPU 性能有关？

降低间隔时长只能作为临时处理方案，这个问题是否还有其他方案能优化一下？

**Comment by saicaca** [comment]
目前 Banner 高度的变化是直接通过直接改变元素高度实现的，这大概是卡顿的源头（触发了 Layout）。晚点我尝试改用 `transform` 实现，应该能解决卡顿问题。

**Comment by saicaca** [comment]
#178 

现在应该好多了
