### ISSUE TITLE
代码块的高亮配置怎么修改，注释灰色有点看不清

### ISSUE THREAD

**Issue by la02w** [saicaca/fuwari#179]
![image](https://github.com/user-attachments/assets/9539b83c-3611-4c88-a542-d596664d9bb5)

**Comment by saicaca** [comment]
请参考 Astro 文档 https://docs.astro.build/zh-cn/guides/markdown-content/#shiki-%E9%85%8D%E7%BD%AE
本主题未对默认的代码高亮做额外配置
