### ISSUE TITLE
backdrop-blur-lg  not working

### ISSUE THREAD

**Issue by Teddy563** [saicaca/fuwari#18]
idk what messes up but the site does not show the blurred card background
![whyplshelp](https://github.com/saicaca/fuwari/assets/19164688/e19a060c-eca7-4178-bc2f-0b75f1c634e8)
in the vercel preview in shows but on the actual site it does not work
   
    .card-base {
        @apply backdrop-blur-lg rounded-[var(--radius-large)] overflow-hidden bg-[var(--card-bg)] transition;
    }

**Comment by saicaca** [comment]
This seems to be a tricky CSS issue. I can't provide a solution here. Maybe you could check the Tailwind docs or StackOverflow for help.
