### ISSUE TITLE
希望增加TOC

### ISSUE THREAD

**Issue by wxydejoy** [saicaca/fuwari#180]
我借鉴国外博主改了下，但我是外行，改的不是很好
![image](https://github.com/user-attachments/assets/554ddb64-28de-4f61-b41a-4abb2ce3b646)

我的仓库链接
https://github.com/wxydejoy/fuwari/tree/7c1532681ee37e67fd6b52427f86a5b6c4c58e3f

相关国外博客
博客  https://blog-template-gray.vercel.app/post/astro-copy-3/  博客代码库 https://github.com/danielcgilibert/blog-template

**Comment by SlimeNull** [comment]
我也加了一个, 效果如下. 感兴趣可以去我仓库看看. https://github.com/slimenull/Blogs

![8c79e62e6532604a381af8c02891128b](https://github.com/user-attachments/assets/a54707d2-d014-420a-9453-b860b7cb2498)

**Comment by saicaca** [comment]
已加入 TOC 支持
