### ISSUE TITLE
New page transition update breaks top menu when banner is disabled

### ISSUE THREAD

**Issue by CarlosCB1986** [saicaca/fuwari#182]
This commit https://github.com/saicaca/fuwari/commit/f0754cae3fd78bc714038e331a38eb903884dec6 has this consequence:
1.- Disable banner
2.- In the main page, scroll down enough so that the top menu is not visible
3.- Once the top menu is not visible click on any of the posts
4.- Once you transition to the post view it will automatically scroll up to the top but the top menu is not shown

**Comment by saicaca** [comment]
Fix in 44fb628737cc858af24442e7b0dd6148b39304c8
