### ISSUE TITLE
Categories and Tags left side sticky menu no top margin when banner enabled

### ISSUE THREAD

**Issue by CarlosCB1986** [saicaca/fuwari#184]
Steps to reproduce:
- Enable banner
- Add enough posts so that main page view has enough margin to scroll down
- Scroll down until Categories and Tags sticky menu sticks on top

This does not happen when banner is disabled. 
This does not happen when scrolling down inside a post even with banner enabled.

**Comment by saicaca** [comment]
Fixed in 93209a5bba754a0e3567e5b575771ee9572b665c
