### ISSUE TITLE
Blue border around post entry on mobile and tablet

### ISSUE THREAD

**Issue by CarlosCB1986** [saicaca/fuwari#189]
Steps to reproduce:
- Go to the main page
- Click on any of the posts
- Blue border appears surrounding the post entry

I have reproduced this issue on iPhone 13 Mini and iPad 9th Gen both on Chrome and Safari.

![18737](https://github.com/user-attachments/assets/99391b31-635d-468f-88d5-f2b4a4fe736d)

**Comment by L4Ph** [comment]
I don't have an iOS device handy, so I'm not sure, but I suspect it's a problem with `-webkit-tap-highlight-color`.
https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-tap-highlight-color

What do you think? @saicaca
