### ISSUE TITLE
update sidebar dynamically

### ISSUE THREAD

**Issue by Ganeshpadmanaban** [saicaca/fuwari#19]
Is there a way to update the tags on the sidebar after opening a post dynamically? 

<img width="1440" alt="image" src="https://github.com/saicaca/fuwari/assets/29490672/30219c7f-8601-4593-b1ef-8df4323402d7">

If possible, can you please guide me how to do that, i can create a PR if you prefer to add it as well? Thanks for the repo, looks amazing!

**Comment by saicaca** [comment]
Thank you for your support! 
Do you mean to display the tags of the current post? Currently, there isn't a feature for that. I plan to redesign the sidebar in the future so I think you don't need to create a PR for that.

**Comment by Ganeshpadmanaban** [comment]
Yes exactly! Thank you!
