### ISSUE TITLE
How can i change image sizes?

### ISSUE THREAD

**Issue by SickHacks** [saicaca/fuwari#190]
Hello, I really like this template. I have set up and configured my page, but I still can't modify the size of the images I upload to my posts. I've tried several ways, but haven't been successful. How do you usually handle this? Thanks in advance. 🌿

**Comment by L4Ph** [comment]
What does resizing an image entail?  px?, aspect ratio?

**Comment by SickHacks** [comment]
Oh sorry, by image size i mean px, widht lenght.

**Comment by L4Ph** [comment]
@SickHacks 
The markdown syntax `![image](https://example.com)` does not allow specifying image height or width. 
To do so, you must use the `<img src="example.jpg" alt="" width="" height="" />`.
however, it's possible that Fuwari is overriding those values.

**Comment by saicaca** [comment]
`<img width="" />` works, but it can only be used for images in the `/public` and remote images.

For local images, you might need to use the `<Image>` components, in MDX files. You will need to add MDX integration manually as it is not included by default.

https://docs.astro.build/en/guides/images/#images-in-mdx-files
https://docs.astro.build/en/guides/integrations-guide/mdx
