### ISSUE TITLE
关于实时更新的问题

### ISSUE THREAD

**Issue by bubbl000** [saicaca/fuwari#194]
![image](https://github.com/user-attachments/assets/c4e24932-2a6d-4b99-90a7-e36c92197d65)
写了一一个博客目录当目录处于左侧栏目的时候 需要右键刷新才会更新当前目录 这个问题需要怎么解决 求助

**Comment by SlimeNull** [comment]
在 astro 配置中加入你的元素即可.

![image](https://github.com/user-attachments/assets/806fc953-1747-48d5-afdc-8534c47caa37)
