### ISSUE TITLE
Using $ symbols in posts breaks in posts

### ISSUE THREAD

**Issue by davidvkimball** [saicaca/fuwari#202]
Here's an example of me using a dollar sign in a blog post: 

![image](https://github.com/user-attachments/assets/d68efc87-f88f-4f2e-ac4f-2114a8d77941)

I'm honestly not sure why it happens. 

As a temporary fix, I wrap dollar amounts like this: `$24`. 

![image](https://github.com/user-attachments/assets/fa39e353-0558-458b-ab51-43860c14ac67)

Any idea why this would occur and what should be done to fix it?

**Comment by SnowAgar25** [comment]
LaTeX inline math mode.
You can use backslashes to escape them.

![image](https://github.com/user-attachments/assets/11133a11-e4ef-4ddf-b75e-625c7a49c4ef)
![image](https://github.com/user-attachments/assets/bfbf9e65-2324-4ec8-8161-970897905813)
