### ISSUE TITLE
主页（Home）页面字体模糊

### ISSUE THREAD

**Issue by CosmoLau** [saicaca/fuwari#203]
目前只发现主页有这个情况，只要在主页（Home），整个页面的字体就是模糊的（除了 NavBar 顶部导航），其他页面是清晰的，以下用 `Profile` 组件截图效果为例：

主页（Home）截图：
![屏幕截图 2024-10-16 163023](https://github.com/user-attachments/assets/41292e87-c939-458c-8c77-22dbe755359b)

其他页面截图：
![屏幕截图 2024-10-16 163004](https://github.com/user-attachments/assets/08298794-43d7-4692-ad3f-43ef5e6d1ae6)

这个问题应该是在 #178 这个 PR 合并后出现的

**Comment by saicaca** [comment]
只在我自己的设备上测试过，Chromium 内核的浏览器有这个问题，Firefox 上未发现。

#178 在主页使用了 `translate` 来移动元素，目前测试的结果是非 4px 的整数倍的 `translate` 会导致文本模糊，越偏离 4px 的整数倍模糊越严重。

18fcf6dd83709beccc45c68a68b8091fe4798b0c 尝试做了修复，但只在我自己的设备上测试过，如果问题依然存在可以重开此 issue。
