### ISSUE TITLE
Issue with categories and github pages

### ISSUE THREAD

**Issue by TomerGamerTV** [saicaca/fuwari#205]
So I set up my blog on GitHub pages and everything seems kinda fine other than the categories, no matter what category I choose it either gives me a 404 error or just breaks the website.

I know what the issue is but I can't find a way to fix it without breaking github pages....

This is my website: https://tomergamertv.github.io/blog/

When entering let's say the examples category it goes to here: https://tomergamertv.github.io/blog/blog/archive/category/Examples/

You can see it got "blog" 2 times, I tried to find where I could fix it in the files but I couldn't find anything.

**Comment by 3kh0** [comment]
Ok, after digging through your code. I think I found the issue in your [`src/utils/url-utils.ts`](https://github.com/TomerGamerTV/blog/blob/main/src/utils/url-utils.ts)

```js
// TomerGamerTV/blog/blob/main/src/utils/url-utils.ts#L19
export function getCategoryUrl(category: string): string {
  if (category === i18n(i18nKey.uncategorized))
    return url('/blog/archive/category/uncategorized/')
  return url(`/blog/archive/category/${category}/`)
}
```

For some reason, `/blog/` is added at the start, which might cause your issues. To compare, the normal branch does not have this added on:

```js
// saicaca/fuwari/main
export function getCategoryUrl(category: string): string {
  if (category === i18n(i18nKey.uncategorized))
    return url('/archive/category/uncategorized/')
  return url(`/archive/category/${category}/`)
}
```

I also wonder if this is an issue with you hosting your blog under a folder, which also seems likely. Either way, this issue is with your configuration and not the project itself.

I would recommend creating a GitHub organization (so you can get a free github.io subdomain) and name it `TomerGamerTV-blog`, then have your blog site under that org so you can access it at `TomerGamerTV-blog.github.io`

**Comment by TomerGamerTV** [comment]
But wouldn't the issue stay the same? I will still have to create a repo in the organization and the story will repeat itself, unless I'm doing something wrong?

Do you have a working fuwari setup on GitHub pages?

**Comment by 3kh0** [comment]
I do not personally use GitHub pages as they are quite restrictive. I would recommend Cloudflare pages as they are free, have great support for frameworks, and do all the heavy lifting for you.

**Comment by TomerGamerTV** [comment]
> I do not personally use GitHub pages as they are quite restrictive. I would recommend Cloudflare pages as they are free, have great support for frameworks, and do all the heavy lifting for you.

Is there a way to change the URL for free and make it less ugly than "blog-92a.pages.dev"?

**Comment by L4Ph** [comment]
@TomerGamerTV 



> Ok, after digging through your code. I think I found the issue in your [`src/utils/url-utils.ts`](https://github.com/TomerGamerTV/blog/blob/main/src/utils/url-utils.ts)
> 
> ```js
> // TomerGamerTV/blog/blob/main/src/utils/url-utils.ts#L19
> export function getCategoryUrl(category: string): string {
>   if (category === i18n(i18nKey.uncategorized))
>     return url('/blog/archive/category/uncategorized/')
>   return url(`/blog/archive/category/${category}/`)
> }
> ```
> 
> For some reason, `/blog/` is added at the start, which might cause your issues. To compare, the normal branch does not have this added on:
> 
> ```js
> // saicaca/fuwari/main
> export function getCategoryUrl(category: string): string {
>   if (category === i18n(i18nKey.uncategorized))
>     return url('/archive/category/uncategorized/')
>   return url(`/archive/category/${category}/`)
> }
> ```
> 
> I also wonder if this is an issue with you hosting your blog under a folder, which also seems likely. Either way, this issue is with your configuration and not the project itself.
> 
> I would recommend creating a GitHub organization (so you can get a free github.io subdomain) and name it `TomerGamerTV-blog`, then have your blog site under that org so you can access it at `TomerGamerTV-blog.github.io`

In the end, as he said, the category page needs to be created as `/archive/category`. 
This is because the routing `/blog/archive/category` does not exist. 
Even if we were to make it `/blog/archive/category`, I think it would require a fairly large change to the codebase, so I don't particularly recommend it.

**Comment by TomerGamerTV** [comment]
> @TomerGamerTV 
> 
> 
> 
> 
> 
> 
> 
> > Ok, after digging through your code. I think I found the issue in your [`src/utils/url-utils.ts`](https://github.com/TomerGamerTV/blog/blob/main/src/utils/url-utils.ts)
> 
> > 
> 
> > ```js
> 
> > // TomerGamerTV/blog/blob/main/src/utils/url-utils.ts#L19
> 
> > export function getCategoryUrl(category: string): string {
> 
> >   if (category === i18n(i18nKey.uncategorized))
> 
> >     return url('/blog/archive/category/uncategorized/')
> 
> >   return url(`/blog/archive/category/${category}/`)
> 
> > }
> 
> > ```
> 
> > 
> 
> > For some reason, `/blog/` is added at the start, which might cause your issues. To compare, the normal branch does not have this added on:
> 
> > 
> 
> > ```js
> 
> > // saicaca/fuwari/main
> 
> > export function getCategoryUrl(category: string): string {
> 
> >   if (category === i18n(i18nKey.uncategorized))
> 
> >     return url('/archive/category/uncategorized/')
> 
> >   return url(`/archive/category/${category}/`)
> 
> > }
> 
> > ```
> 
> > 
> 
> > I also wonder if this is an issue with you hosting your blog under a folder, which also seems likely. Either way, this issue is with your configuration and not the project itself.
> 
> > 
> 
> > I would recommend creating a GitHub organization (so you can get a free github.io subdomain) and name it `TomerGamerTV-blog`, then have your blog site under that org so you can access it at `TomerGamerTV-blog.github.io`
> 
> 
> 
> In the end, as he said, the category page needs to be created as `/archive/category`. 
> 
> This is because the routing `/blog/archive/category` does not exist. 
> 
> Even if we were to make it `/blog/archive/category`, I think it would require a fairly large change to the codebase, so I don't particularly recommend it.

So if it's so buggy do deploy on GitHub pages it should be noted in the wiki I think or removed

**Comment by L4Ph** [comment]
@TomerGamerTV 
![image](https://github.com/user-attachments/assets/8558e4ed-22f2-49a1-ab46-b27e8a8253b3)

I don't know what you're referring to as a "bug", but I think it's at least a problem caused by your changes. 
I cloned your repository locally and checked, 
but I think it's working correctly as Astro, and by extension, as Javascript/Typescript.

For comparison, I will leave a repository that deploys Fuwari with default settings to GitHub Pages for reproduction.
https://l4ph.github.io/fuwari-repo-github-pages/
https://github.com/L4Ph/fuwari-repo-github-pages

**Comment by TomerGamerTV** [comment]
> @TomerGamerTV 
> 
> ![image](https://github.com/user-attachments/assets/8558e4ed-22f2-49a1-ab46-b27e8a8253b3)
> 
> 
> 
> I don't know what you're referring to as a "bug", but I think it's at least a problem caused by your changes. 
> 
> I cloned your repository locally and checked, 
> 
> but I think it's working correctly as Astro, and by extension, as Javascript/Typescript.
> 
> 
> 
> For comparison, I will leave a repository that deploys Fuwari with default settings to GitHub Pages for reproduction.
> 
> https://l4ph.github.io/fuwari-repo-github-pages/
> 
> https://github.com/L4Ph/fuwari-repo-github-pages
> 
> 

Huh weird I don't see the bug I experience in your GitHub page.... I will compare later what's wrong

**Comment by L4Ph** [comment]
@3kh0 has written it, but it needs to be combined with fuwari/main.

```diff
export function getCategoryUrl(category: string): string {
  if (category === i18n(i18nKey.uncategorized))
-    return url('/blog/archive/category/uncategorized/')
+    return url('/archive/category/uncategorized/')
-  return url(`/blog/archive/category/${category}/`)
+  return url(`/archive/category/${category}/`)
}
```

https://github.com/TomerGamerTV/blog/blob/d215b796b91aba224912fb9731ec88ff0a8ff715/src/utils/url-utils.ts#L19-L23

**Comment by TomerGamerTV** [comment]
> @3kh0 has written it, but it needs to be combined with fuwari/main.
> 
> 
> 
> ```diff
> 
> export function getCategoryUrl(category: string): string {
> 
>   if (category === i18n(i18nKey.uncategorized))
> 
> -    return url('/blog/archive/category/uncategorized/')
> 
> +    return url('/archive/category/uncategorized/')
> 
> -  return url(`/blog/archive/category/${category}/`)
> 
> +  return url(`/archive/category/${category}/`)
> 
> }
> 
> ```
> 
> 
> 
> https://github.com/TomerGamerTV/blog/blob/d215b796b91aba224912fb9731ec88ff0a8ff715/src/utils/url-utils.ts#L19-L23
> 
> 
> 
> 

Do you know how I can combine it into my repo for now?
