### ISSUE TITLE
I want to stop using corepack.

### ISSUE THREAD

**Issue by L4Ph** [saicaca/fuwari#228]
Since it has been deprecated in Node.js Proposal, I would like to abolish it considering its future prospects. 
Personally, I would like to adopt [moonrepo/proto](https://moonrepo.dev/proto) as a candidate. 
Alternatively, the following method is also acceptable.
https://pnpm.io/only-allow-pnpm

https://github.com/saicaca/fuwari/blob/87547fca869840b8597199f5134bc1a873a4f5d5/package.json#L73

**Comment by 3kh0** [comment]
I think just making people use pnpm using the preinstall script is a better way of doing things

**Comment by L4Ph** [comment]
> I think just making people use pnpm using the preinstall script is a better way of doing things

I also think so.
However, the problem that arises here is how to manage the version of pnpm.
@3kh0
