### ISSUE TITLE
Two small bugs

### ISSUE THREAD

**Issue by Yuhanawa** [saicaca/fuwari#242]
1. https://github.com/saicaca/fuwari/blob/079abbc9650b11493e7f3da697cb9cbc0d34833b/src/plugins/rehype-component-github-card.mjs#L76

```js
        if (data.license?.spdx_id) {
          document.getElementById('${cardUuid}-license').innerText = data.license?.spdx_id
        } else {
          document.getElementById('${cardUuid}-license').classList.add = "no-license" // here
        };
``` 

it should be
```js
document.getElementById('${cardUuid}-license').innerText = "no-license"
```

Here is a better way:
```js
document.getElementById('${cardUuid}-license').innerText = data.license?.spdx_id || "no-license";
```

2. https://github.com/saicaca/fuwari/blob/079abbc9650b11493e7f3da697cb9cbc0d34833b/src/styles/markdown-extend.styl#L242
missing `.` in front of the github-logo
```styl
.card-github, .gc-description, .gc-titlebar, .gc-stars, .gc-forks, .gc-license, .gc-avatar, github-logo
```
=>
```styl
.card-github, .gc-description, .gc-titlebar, .gc-stars, .gc-forks, .gc-license, .gc-avatar, .github-logo
```
I very like fuwari and tried to write my own Astro theme by referencing it, so I found that

**Comment by saicaca** [comment]
Fixed. Thanks for spotting the bugs!
