### ISSUE TITLE
TOC Highlight handles incorrectly a specific scenario

### ISSUE THREAD

**Issue by CarlosCB1986** [saicaca/fuwari#249]
A markdown file with this structure..
```
# This is a test
This is a test

## This is a test
This is a test

### This is a test
This is a test
```

..is generating wrong TOC highlight display

<img width="400" alt="image" src="https://github.com/user-attachments/assets/0a5e03ba-6bc7-40be-9bcb-15b62d21d697">

**Comment by saicaca** [comment]
Fixed in cbf17e880d95a3cf76c0cd24fb8a0fc940c83641
