### ISSUE TITLE
该模板能否基于Notion实现？

### ISSUE THREAD

**Issue by 784494706** [saicaca/fuwari#31]
- 模板很棒！丝滑！流畅!
- Github有一个基于NEXTJS框架开发的[NotionNext](https://github.com/tangly1024/NotionNext)-Notion建站工具
- fuwari模板是否可以适用到Notion
- 再次感谢作者，我简直太喜欢这个模板了！
---
- Templates are awesome! Silky! Smooth!
- Github has a [NotionNext](https://github.com/tangly1024/NotionNext)-Notion website building tool developed based on the NEXTJS framework
- Whether the fuwari template can be applied to Notion
- Thanks again to the author, I absolutely love this template!

**Comment by saicaca** [comment]
感谢支持！抱歉暂时没有开发 Notion Next 主题或者适配 Notion API 的计划
Thank you for your support! There are currently no plans for a Notion Next theme or adapting the Notion API.

**Comment by 784494706** [comment]
> 感谢支持！抱歉暂时没有开发 Notion Next 主题或者适配 Notion API 的计划 Thank you for your support! There are currently no plans for a Notion Next theme or adapting the Notion API.

It's okay, I've already sent an email to the developers of Notion Next, hoping they can help with the adaptation, if possible!
