### ISSUE TITLE
Firefox 下文章 meta 标签样式错乱

### ISSUE THREAD

**Issue by kisnows** [saicaca/fuwari#41]
Chrome下没有问题，但是在最新版的 Firefox 下有问题。
![image](https://github.com/saicaca/fuwari/assets/9394000/8e423070-92e7-4da6-83c1-612468a0c859)

**Comment by Samxamnom** [comment]
I fixed it by adding `whitespace-nowrap` to the `with-divider` component. Probably not the most elegant solution; but it works. 

See: https://github.com/Samxamnom/Samxamnom.github.io/commit/b333466ffd9c683ae4f12240b99803d92a362c31#diff-e49ad2b45728c5139fcce0c5b309b5c05e54a89977dada8c726fd5fb313df712L74-R74

**Comment by saicaca** [comment]
Fixed in 5dd1287255a53ac92477883259fe49b1b25414db
