### ISSUE TITLE
[BUG] Markdown render issue for code block

### ISSUE THREAD

**Issue by JoeyC-Dev** [saicaca/fuwari#44]
Test content:

<pre><code>---
title: Test
published: 2024-04-09
description: Test
tags: ["Test"]
category: How-to
draft: false
---
Content  
2. Try access secrets again
```bash
kubectl get secrets -n kube-system
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXXXXXXX to authenticate.
NAME                     TYPE                            DATA   AGE
bootstrap-token-sw3rck   bootstrap.kubernetes.io/token   4      35h
konnectivity-certs       Opaque                          3      35h
```
> **⚠ IMPORTANT**  
>  Due to the design of 
</code></pre>

**Old theme:**
![image](https://github.com/saicaca/fuwari/assets/142381267/dc73cc84-6a38-45c1-9dcf-f8cc9d98a4a7)

**New theme:** ("Line 6" appears)
![image](https://github.com/saicaca/fuwari/assets/142381267/bb820cec-538f-4ebc-a1e1-75535813ebe1)

I tested on VSC preview, the `line 6` also not appearing:  
![image](https://github.com/saicaca/fuwari/assets/142381267/5bdd00ac-2344-4118-adaf-9ab8f3ea8479)

Tested on other code blocks, and found the extra lines are not selectable:
![image](https://github.com/saicaca/fuwari/assets/142381267/121ffab3-84a8-43c9-83f4-23ea59bde489)

I don't think I have my Markdown format wrong. **So this `line 6` should be rendered for error.**

**Comment by JoeyC-Dev** [comment]
Not sure about the root cause, but I solved it by switching from npm to pnpm.

**Comment by saicaca** [comment]
This happened after Astro was updated to `3.5`, which appends an empty `<span class="line">` to the code block. I have no idea how to fix it for now.
