### ISSUE TITLE
[Feature Request] Add Meta Description Tag to Web Pages

### ISSUE THREAD

**Issue by LibraryLibrarian** [saicaca/fuwari#49]
Upon checking the meta tags of the generated site, I found that the description is still set to its default configuration. This often functions as a headline when sharing the website externally, so it seems undesirable for it to remain in its default state.
https://github.com/saicaca/fuwari/blob/0676b01b6aec9915ac89023b84307d0ef76abde4/src/layouts/Layout.astro#L73

As for the actual modifications, we have a clear idea of what needs to be done and are currently working on making those changes. We plan to submit a pull request after completing these adjustments, so your review would be appreciated.

**Comment by JoeyC-Dev** [comment]
I appreciate the hard work of the author. But after days of modification, I feel like the dev is concentrating on layout modification (and it does look better!). but forgot the basic functionality while it looks like it is for production use. 
I hope the basic function can be complete ASAP cuz it is announced that the old theme is not actively maintained, and users will be inclined to use this theme based on that announcement.

**Comment by LibraryLibrarian** [comment]
It seems someone else has already addressed this, so I will close this issue.
https://github.com/saicaca/fuwari/issues/55
