### ISSUE TITLE
how to delete the post

### ISSUE THREAD

**Issue by ziv314** [saicaca/fuwari#52]
add a post：

`pnpm new-post  xxx.md `

please how to delete a post？

**Comment by Hongbusi** [comment]
Manually delete?

**Comment by anonyoroshi** [comment]
I haven't tried it, but I think you can read draft articles on the WEBUI by manually adding md files. and 
you can manually deleteing md files.

i think this FuwariSystems articles don't need to add flags to the database or settingfiles

On Linux, you can delete them with rm /src/content/posts/draft_test.md or something like that. I think you can also automate it by writing your own code.

**Comment by anonyoroshi** [comment]
/src/content/posts/draft_test.md

pnpm new-post <filename>
↓
package.json
  "scripts": {
・・・
    "new-post": "node scripts/new-post.js",
・・・
  },
  ↓
/scripts/new-post.js
/* This is a script to create a new post markdown file with front-matter */
・・・

I haven't tried it, new-post.js seems to simply create md file
i think this FuwariSystems articles don't need to add flags to the database or settingfiles
so you can delete Manually or something

**Comment by saicaca** [comment]
Just manually delete the markdown file. We don't need a command for it. 

The purpose of the `new-post` command is to automatically create the Front-matter, so you don't need to copy it from elsewhere.
