### ISSUE TITLE
ERROR ON SITE AND BASE URL CONFIGURATION

### ISSUE THREAD

**Issue by gtamilvanan17** [saicaca/fuwari#58]
Hello there, Hope you're doing good.

I tried deploying this project in my github repo `my-repo`. But the href for all is not wokring as expected. When I click on "Archieve" or any other button which has routing, it is looking for `username.github.io/archieve`. 
But what I expected is `username.github.io/my-repo/archieve`.

My configurations for `astro.config.mjs` file.

export default defineConfig({
  site: "https://username.github.io/my-repo/",
  base: "/my-repo/",

Can someone help me in this issue to get resolved.

Thanks in advance.

**Comment by saicaca** [comment]
Thanks for your support! This will be fixed later.

**Comment by saicaca** [comment]
410902a76712155fe7dc998b0256d81516c5f6b8 should have fixed the issue.

**Comment by gtamilvanan17** [comment]
Hi @saicaca ,

Thanks for sorting out this.
