### ISSUE TITLE
在本地为封面指定图像时，路径会中断。

### ISSUE THREAD

**Issue by Katsuyuki-Karasawa** [saicaca/fuwari#6]
用标记符指定时也会出错。
```bash
 error   files[normalizedPath] is not a function
  File:
    C:\Users\**\**\**\src\components\misc\ImageBox.astro:22:38
  Code:
    21 |     let normalizedPath = "../../" + path.normalize(src).replace(/\\/g, "/");
    > 22 |     img = await (files[normalizedPath])();
         |                                      ^
      23 | }
      25 | ---
```

**Comment by saicaca** [comment]
应该是图片路径填写不正确导致的，抱歉文档还没有对此进行说明
封面图路径的填写方式如下：
1. 以 `http://` 或 `https://` 为前缀的路径会被识别远程图像
2. 以 `/` 为前缀的路径会引用 `public/` 下的文件，如填写 `/image.jpg` 会引用 `/public/image.jpg`
3. 不包含上述前缀的路径则会引用 `src/` 下的文件，通过这种方法引入的图像能够被自动优化所以推荐使用。暂时不支持填写相对路径，之后会修复（Markdown 正文里可以填写相对路径）
