### ISSUE TITLE
开发环境下不显示图片

### ISSUE THREAD

**Issue by Rabbit937** [saicaca/fuwari#75]
1. 正常安装依赖
2. ![image](https://github.com/saicaca/fuwari/assets/122858631/5ef444b5-0988-4204-8d51-23367137ab92)

**Comment by Rabbit937** [comment]
![image](https://github.com/saicaca/fuwari/assets/122858631/9d8cd1bb-dfaa-41e3-b292-ab8360f67fbb)
重新执行`pnpm add sharp`安装之后，再次运行还是相同的问题

**Comment by 1999-xinz** [comment]
删除node_modules，重新pnpm install试试；我也遇到这个/_image安装时为500的情况的，就是这样解决的。

**Comment by Rabbit937** [comment]
> 删除node_modules，重新pnpm install试试；我也遇到这个/_image安装时为500的情况的，就是这样解决的。
应该是我电脑环境的问题，换其他电脑没有问题。

**Comment by CosmoLau** [comment]
我也遇到了这个问题，查了 Astro 和 Sharp 的 issue，通过改 node 版本和降 sharp 版本都没法解决，还是显示不了图片。

目前只能根据 https://docs.astro.build/zh-cn/reference/errors/missing-sharp/ 提供的办法来禁用图片处理服务。

在 `astro.config.mjs` 中添加代码：

```js
import { defineConfig, passthroughImageService } from "astro/config";
export default defineConfig({
 image: {
   service: passthroughImageService(),
 },
});
```

**Comment by Rabbit937** [comment]
@CosmoLau 好的，谢谢，我试一下

**Comment by CosmoLau** [comment]
@Rabbit937  才发现有个 PR 修复了这个问题，但是 PR 还没合并，你可以试试这个 https://github.com/saicaca/fuwari/pull/92
