### ISSUE TITLE
A consultation regarding the issue with relative paths.

### ISSUE THREAD

**Issue by Katsuyuki-Karasawa** [saicaca/fuwari#8]
Hello @saicaca !
I'm currently working on an issue with relative paths.
I found a library called [astro-relative-links](https://github.com/ixkaito/astro-relative-links) and when I tried using it, I was able to confirm that it works fine with relative paths.

I believe it's working correctly in my current branch, but if there are any issues or concerns, I would appreciate a review.

If there don't appear to be any issues, I plan to merge it into my current `main` branch and then create a pull request through the `main` branch.

[my path fix branch](https://github.com/Katsuyuki-Karasawa/fuwari/blob/df1e3455e7f252e82c0b1028f9a6a24ed163ee2b/src/components/misc/ImageBox.astro)

**Comment by Katsuyuki-Karasawa** [comment]
ok 
I found critical issue

- [ ] word count missing
- [ ] minutes count missing
- [ ] preview image missing

**Comment by saicaca** [comment]
Hello!
I'm sorry, I didn't fully understand the purpose of introducing `astro-relative-links` here. Is it to make relative paths work for cover images of articles?

**Comment by Katsuyuki-Karasawa** [comment]
Yes, it is.
I'm having a bit of a problem with this, as I can't use relative paths for images at the moment.

Also, the biggest problem is that the images are not optimized.
If I load from `public/`, the images will not be optimized or compress, so I would prefer to use relative paths.

Other than that, I have the article as `src/content/posts/[slug]/index.md` and `. /image.jpg` as I want to load it as `.

**Comment by saicaca** [comment]
I think I've figured out a solution to this without using `astro-relative-links`. I will try when I'm free in the coming days, so maybe you don't need to do it for now.

**Comment by Katsuyuki-Karasawa** [comment]
ok I understand

**Comment by saicaca** [comment]
Fixed in [relative-path](https://github.com/saicaca/fuwari/tree/relative-path) branch. The `image` path in front-matter is now relative to the markdown file instead of starting from `src`.

I think we can get #7 done first, to avoid creating new conflicts for you.
