### ISSUE TITLE
请问如何在这项目中添加点赞功能， 对每篇blog有点赞的统计和显示

### ISSUE THREAD

**Issue by ziv1441** [saicaca/fuwari#89]

**Comment by saicaca** [comment]
本项目作为静态博客主题本身不提供点赞功能，可以使用 [Waline](https://waline.js.org/guide/features/reaction.html) 这类的第三方服务自行添加

**Comment by ziv1441** [comment]
请教一个问题: 点赞功能可以用astro的DB功能实现么

**Comment by saicaca** [comment]
可以，只是我目前不太打算用

**Comment by ziv1441** [comment]
好的，谢谢。我按照您建议的方向试试Waline
