### ISSUE TITLE
Bug of design in post meta component.

### ISSUE THREAD

**Issue by n1ckisthereu** [saicaca/fuwari#93]
Bug:
![image](https://github.com/saicaca/fuwari/assets/75399141/27bb2e3b-75bd-401f-b231-76107ca0d326)

Expected:
![image](https://github.com/saicaca/fuwari/assets/75399141/80b03dd7-e38b-4196-a0ee-fceb5217b27d)

**Comment by n1ckisthereu** [comment]
In this new adjust, I remove the margin of tag, for the best design, if not remove margin the section of categories stays very large space.

![image](https://github.com/saicaca/fuwari/assets/75399141/edd78457-0b22-404a-9607-aa9867c25da2)

**Comment by saicaca** [comment]
Fixed in 5dd1287255a53ac92477883259fe49b1b25414db
