### ISSUE TITLE
To avoid getting the extra new empty line in Fenced Code Block

### ISSUE THREAD

**Issue by gtamilvanan17** [saicaca/fuwari#99]
Hi Team,

Today while I am practicing with the application, I facing a small issue, that an extra empty line in **`fenced code blobk`**. Attached the screenshot below for the reference.

![image](https://github.com/saicaca/fuwari/assets/121214873/4b3228ea-ec2c-4e40-80ee-7dbaf5f89e2c)

And here's the code I used for above fence code block.

![image](https://github.com/saicaca/fuwari/assets/121214873/8511389f-1ba8-4499-8b19-47f346ced223)

Kindly someone please help to avoid/remove the extra line from the fence code block.

Special Mentions:
@saicaca 

**Thanks in advance**

**Comment by akbarhmu** [comment]
You can try to hide the last empty line using CSS, you can add this into your Markdown.astro file

```css
span.line:last-child:empty { display: none; }
```

**Comment by gtamilvanan17** [comment]
A big thanks @akbarhmu , it's actually working.
![image](https://github.com/saicaca/fuwari/assets/121214873/18a3eae3-445f-444d-a46d-58b379a87bc8)
